// DevPulse AI — Frontend Logic
const API = 'http://127.0.0.1:5000';

let currentRepoUrl = '';
let currentRepoData = null;

// ── Utilities ─────────────────────────────────────────────────────────────────

function $(id) { return document.getElementById(id); }

function showLoading(msg = 'Analyzing...') {
  $('loading-text').textContent = msg;
  $('loading').classList.remove('hidden');
  $('results').classList.add('hidden');
}

function hideLoading() {
  $('loading').classList.add('hidden');
}

function showError(msg) {
  hideLoading();
  $('results').innerHTML = `<div class="result-error">❌ ${msg}</div>`;
  $('results').classList.remove('hidden');
}

function setRepoStatus(msg, type) {
  const el = $('repo-status');
  el.textContent = msg;
  el.className = `repo-status repo-status-${type}`;
  el.classList.remove('hidden');
}

function enableModuleButtons() {
  ['btn-summary', 'btn-context', 'btn-pr', 'btn-debt', 'btn-incident', 'btn-readme', 'btn-fix'].forEach(id => {
    $(id).disabled = false;
  });
}

async function apiFetch(endpoint, body) {
  const res = await fetch(`${API}${endpoint}`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!res.ok) throw new Error(json.error || `HTTP ${res.status}`);
  return json.data;
}

// ── Load Repository ───────────────────────────────────────────────────────────

async function loadRepo() {
  const url = $('repo-url').value.trim();
  if (!url) { setRepoStatus('Please enter a GitHub repository URL.', 'error'); return; }

  $('load-btn').disabled = true;
  setRepoStatus('Loading repository...', 'info');
  $('repo-card').classList.add('hidden');
  $('results').classList.add('hidden');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch('/load-repo', { repo_url: url });

    currentRepoUrl = url;
    currentRepoData = data;

    // Populate repo card
    $('rc-name').textContent = data.full_name || data.name;
    
    // Add indicator for auto-generated descriptions
    let description = data.description;
    const isAutoGenerated = description && (
      description.includes('application') ||
      description.includes('project') ||
      description.includes('service') ||
      description.includes('built with') ||
      description.includes('architecture') ||
      description.includes('Modern') ||
      description.includes('Software')
    ) && !description.includes('No description');
    
    if (isAutoGenerated) {
      $('rc-desc').innerHTML = `${description} <span class="ai-generated-badge">AI-generated</span>`;
    } else {
      $('rc-desc').textContent = description;
    }
    
    $('rc-lang').textContent = data.language;
    $('rc-stars').textContent = `⭐ ${data.stars.toLocaleString()}`;
    $('rc-files').textContent = `📁 ${data.files.length} items`;

    $('repo-card').classList.remove('hidden');
    enableModuleButtons();
    setRepoStatus(`✅ Repository loaded — ${data.files.length} items found`, 'success');
  } catch (e) {
    setRepoStatus(`❌ ${e.message}`, 'error');
  } finally {
    $('load-btn').disabled = false;
  }
}

// Allow Enter key on repo input
$('repo-url').addEventListener('keydown', e => { if (e.key === 'Enter') loadRepo(); });

// ── Repo Summary (Unified Intelligence) ───────────────────────────────────────

async function runRepoSummary() {
  if (!currentRepoUrl) return;

  showLoading('Running unified AI analysis...');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch('/repo-summary', { repo_url: currentRepoUrl });
    hideLoading();
    renderRepoSummary(data);
  } catch (e) {
    showError(e.message);
  }
}

// ── Module Runner ─────────────────────────────────────────────────────────────

async function runModule(endpoint) {
  if (!currentRepoUrl) return;

  const labels = {
    'code-context': 'Analyzing architecture...',
    'pr-review': 'Running health checks...',
    'debt': 'Scanning for technical debt...',
  };

  showLoading(labels[endpoint] || 'Analyzing...');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch(`/${endpoint}`, { repo_url: currentRepoUrl });
    hideLoading();

    if (endpoint === 'code-context') renderCodeContext(data);
    else if (endpoint === 'pr-review') renderPRGuardian(data);
    else if (endpoint === 'debt') renderDebtRadar(data);
  } catch (e) {
    showError(e.message);
  }
}

// ── Incident Form ─────────────────────────────────────────────────────────────

function showIncidentForm() {
  $('incident-form').classList.remove('hidden');
  $('results').classList.add('hidden');
  $('incident-form').scrollIntoView({ behavior: 'smooth' });
}

function hideIncidentForm() {
  $('incident-form').classList.add('hidden');
}

async function runIncident() {
  const errorMsg = $('error-msg').value.trim();
  const codeSnippet = $('code-snippet').value.trim();

  if (!errorMsg) { alert('Please enter an error message.'); return; }
  if (!codeSnippet) { alert('Please enter a code snippet.'); return; }

  showLoading('Diagnosing bug...');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch('/incident', { error_message: errorMsg, code_snippet: codeSnippet });
    hideLoading();
    renderIncident(data);
  } catch (e) {
    showError(e.message);
  }
}

// ── 🔥 NEW: Generate README ───────────────────────────────────────────────────

async function generateReadme() {
  if (!currentRepoUrl) return;

  showLoading('Generating professional README...');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch('/generate-readme', { repo_url: currentRepoUrl });
    hideLoading();
    renderReadme(data);
  } catch (e) {
    showError(e.message);
  }
}

// ── 🔥 NEW: Fix My Repo ───────────────────────────────────────────────────────

async function fixMyRepo() {
  if (!currentRepoUrl) return;

  showLoading('Analyzing and generating fixes...');
  $('incident-form').classList.add('hidden');

  try {
    const data = await apiFetch('/fix-repo', { repo_url: currentRepoUrl });
    hideLoading();
    renderFixes(data);
  } catch (e) {
    showError(e.message);
  }
}

// ── Renderers ─────────────────────────────────────────────────────────────────

function card(title, content) {
  return `<div class="result-card"><h3 class="result-card-title">${title}</h3>${content}</div>`;
}

function badge(text, cls) {
  return `<span class="badge badge-${cls}">${text}</span>`;
}

function severityBadge(sev) {
  const map = { critical: 'critical', high: 'high', medium: 'medium', low: 'low' };
  return badge(sev.toUpperCase(), map[sev.toLowerCase()] || 'low');
}

function showResults(html) {
  $('results').innerHTML = html;
  $('results').classList.remove('hidden');
  $('results').scrollIntoView({ behavior: 'smooth' });
}

// --- Code Context ---
function renderCodeContext(d) {
  const techPills = (d.techStack || []).map(t => `<span class="pill">${t}</span>`).join('');
  const moduleRows = (d.modules || []).map(m =>
    `<tr><td class="td-name">${m.name}</td><td class="td-desc">${m.purpose}</td></tr>`
  ).join('');

  showResults(`
    <div class="results-header">
      <h2>📊 Code Context — ${d.repoName}</h2>
    </div>
    ${card('🏗️ Architecture', `
      <p class="arch-type">${d.architecture}</p>
      <p class="arch-desc">${d.architectureDescription}</p>
    `)}
    ${card('💻 Tech Stack', `<div class="pill-group">${techPills || '<em>Not detected</em>'}</div>`)}
    ${moduleRows ? card('📦 Detected Modules & Files', `
      <table class="result-table">
        <thead><tr><th>Name</th><th>Purpose</th></tr></thead>
        <tbody>${moduleRows}</tbody>
      </table>
    `) : ''}
    ${card('📈 Stats', `
      <div class="stat-row">
        <div class="stat"><span class="stat-val">${d.totalFiles}</span><span class="stat-label">Root Items</span></div>
        <div class="stat"><span class="stat-val">${(d.techStack || []).length}</span><span class="stat-label">Technologies</span></div>
        <div class="stat"><span class="stat-val">${(d.modules || []).length}</span><span class="stat-label">Modules Found</span></div>
      </div>
    `)}
  `);
}

// --- PR Guardian ---
function renderPRGuardian(d) {
  const scoreClass = d.score >= 80 ? 'score-good' : d.score >= 60 ? 'score-warn' : 'score-bad';

  const issueRows = (d.issues || []).map(i => `
    <div class="check-item check-fail">
      <div class="check-top">
        ${severityBadge(i.severity)}
        <strong>${i.check}</strong>
      </div>
      <p>${i.message}</p>
      <p class="suggestion">💡 ${i.suggestion}</p>
    </div>
  `).join('');

  const passedRows = (d.passed || []).map(p => `
    <div class="check-item check-pass">
      <span class="check-tick">✅</span> <strong>${p.check}</strong> — ${p.message}
    </div>
  `).join('');

  showResults(`
    <div class="results-header">
      <h2>🔍 PR Guardian — Repository Health</h2>
    </div>
    ${card('📊 Health Score', `
      <div class="score-display">
        <span class="score-number ${scoreClass}">${d.score}</span>
        <span class="score-label">/ 100 — ${d.verdict}</span>
      </div>
      <div class="score-bar-bg"><div class="score-bar ${scoreClass}" style="width:${d.score}%"></div></div>
      <p class="score-meta">${d.passedCount} checks passed · ${d.issueCount} issues found</p>
    `)}
    ${d.issues.length ? card(`⚠️ Issues (${d.issueCount})`, issueRows) : ''}
    ${d.passed.length ? card(`✅ Passed (${d.passedCount})`, passedRows) : ''}
  `);
}

// --- Incident Whisperer ---
function renderIncident(d) {
  const steps = (d.reproductionSteps || []).map((s, i) => `<li>${s}</li>`).join('');

  showResults(`
    <div class="results-header">
      <h2>🐛 Incident Whisperer</h2>
      <div>${severityBadge(d.severity)} <span class="badge badge-type">${d.errorType}</span></div>
    </div>
    ${card('🎯 Root Cause', `<p class="root-cause-text">${d.rootCause}</p>`)}
    ${card('📖 Explanation', `<p>${d.explanation}</p>`)}
    ${card('💡 Fix', `<p>${d.fix}</p>`)}
    ${d.updatedCode ? card('✅ Updated Code', `<pre class="code-block">${escHtml(d.updatedCode)}</pre>`) : ''}
    ${steps ? card('🔄 Reproduction Steps', `<ol class="steps-list">${steps}</ol>`) : ''}
  `);
}

// --- Debt Radar ---
function renderDebtRadar(d) {
  const debtClass = { Low: 'score-good', Medium: 'score-warn', High: 'score-bad', Critical: 'score-bad' }[d.debtLevel] || 'score-warn';
  const debtPct = Math.min(100, d.debtScore);

  const issueRows = (d.issues || []).map(i => `
    <div class="check-item check-fail">
      <div class="check-top">
        ${severityBadge(i.severity)}
        <strong>${i.type}</strong>
        ${i.file ? `<code class="file-tag">${i.file}</code>` : ''}
      </div>
      <p>${i.detail}</p>
      <p class="suggestion">💡 ${i.suggestion}</p>
    </div>
  `).join('');

  const suggestionList = (d.suggestions || []).map(s => `<li>${s}</li>`).join('');

  showResults(`
    <div class="results-header">
      <h2>⚠️ Debt Radar — Technical Debt Analysis</h2>
    </div>
    ${card('📊 Debt Score', `
      <div class="score-display">
        <span class="score-number ${debtClass}">${d.debtScore}</span>
        <span class="score-label">/ 100 — ${d.debtLevel} Debt</span>
      </div>
      <div class="score-bar-bg"><div class="score-bar ${debtClass}" style="width:${debtPct}%"></div></div>
      <div class="severity-counts">
        ${Object.entries(d.severityCounts || {}).map(([k, v]) =>
          v > 0 ? `<span class="badge badge-${k}">${k}: ${v}</span>` : ''
        ).join('')}
      </div>
    `)}
    ${d.issues.length ? card(`🔍 Issues Found (${d.totalIssues})`, issueRows) : card('✅ No Issues', '<p>No technical debt issues detected.</p>')}
    ${suggestionList ? card('📋 Prioritized Suggestions', `<ol class="steps-list">${suggestionList}</ol>`) : ''}
  `);
}

// --- Repo Summary (Unified Intelligence) ---
function renderRepoSummary(data) {
  const summary = data.summary;
  const details = data.details;
  
  // Determine verdict color
  const verdictColors = {
    'Excellent': 'verdict-excellent',
    'Good': 'verdict-good',
    'Moderate Risk': 'verdict-moderate',
    'High Risk': 'verdict-high',
    'Critical': 'verdict-critical'
  };
  const verdictClass = verdictColors[summary.verdict] || 'verdict-moderate';
  
  // Score color
  const scoreClass = summary.overallScore >= 80 ? 'score-good' : 
                     summary.overallScore >= 60 ? 'score-warn' : 'score-bad';
  
  // Risk factors
  const riskRows = (summary.riskFactors || []).map(r => `
    <div class="risk-item">
      ${severityBadge(r.severity)}
      <div class="risk-content">
        <strong>${r.factor}</strong>
        <p>${r.impact}</p>
      </div>
    </div>
  `).join('');
  
  // Strengths
  const strengthRows = (summary.strengths || []).map(s => `
    <div class="strength-item">
      <span class="strength-icon">✓</span>
      <div class="strength-content">
        <strong>${s.strength}</strong>
        <p>${s.detail}</p>
      </div>
    </div>
  `).join('');
  
  // Top fixes
  const fixRows = (summary.topFixes || []).map((f, i) => `
    <div class="fix-item fix-priority-${f.priority}">
      <div class="fix-header">
        <span class="fix-number">${i + 1}</span>
        <strong>${f.action}</strong>
        <span class="badge badge-${f.impact.toLowerCase()}">${f.impact}</span>
      </div>
      <p class="fix-reason">${f.reason}</p>
      <p class="fix-suggestion">💡 ${f.suggestion}</p>
    </div>
  `).join('');
  
  showResults(`
    <!-- AI Summary Card (Hero) -->
    <div class="ai-summary-hero">
      <div class="ai-hero-header">
        <h2>🧠 AI Project Intelligence</h2>
        <span class="confidence-badge">Confidence: ${summary.confidence}%</span>
      </div>
      
      <div class="ai-hero-content">
        <div class="ai-score-section">
          <div class="ai-score-display">
            <span class="ai-score-number ${scoreClass}">${summary.overallScore}</span>
            <span class="ai-score-label">/100</span>
          </div>
          <div class="ai-verdict ${verdictClass}">${summary.verdict}</div>
          <div class="ai-score-bar-bg">
            <div class="ai-score-bar ${scoreClass}" style="width:${summary.overallScore}%"></div>
          </div>
        </div>
        
        <div class="ai-summary-text">
          <h3>Summary</h3>
          <p>${summary.summary}</p>
          <div class="ai-metrics">
            <span class="ai-metric">
              <span class="metric-icon">🏗️</span>
              ${summary.projectInfo.architecture}
            </span>
            <span class="ai-metric">
              <span class="metric-icon">💻</span>
              ${summary.projectInfo.language}
            </span>
            <span class="ai-metric">
              <span class="metric-icon">📁</span>
              ${summary.metrics.totalFiles} files
            </span>
          </div>
        </div>
      </div>
    </div>
    
    <!-- 🔥 NEW: Impact Simulator -->
    ${summary.improvementPotential ? card('🚀 Impact Simulator', `
      <div class="impact-simulator">
        <p class="impact-message">${summary.improvementPotential.message}</p>
        <div class="impact-visualization">
          <div class="impact-current">
            <span class="impact-label">Current Score</span>
            <span class="impact-score ${scoreClass}">${summary.improvementPotential.currentScore}</span>
          </div>
          <div class="impact-arrow">
            <svg width="60" height="24" viewBox="0 0 60 24">
              <path d="M 5 12 L 45 12 M 40 7 L 50 12 L 40 17" stroke="currentColor" stroke-width="2" fill="none"/>
            </svg>
            <span class="impact-gain">${summary.improvementPotential.scoreGain}</span>
          </div>
          <div class="impact-projected">
            <span class="impact-label">Projected Score</span>
            <span class="impact-score score-good">${summary.improvementPotential.projectedScore}</span>
          </div>
        </div>
      </div>
    `) : ''}
    
    <!-- 🔥 NEW: Team Risk Statement -->
    ${summary.teamRiskStatement ? card('⚠️ Team Risk Assessment', `
      <div class="team-risk-statement">
        <p class="risk-statement-text">${summary.teamRiskStatement}</p>
      </div>
    `) : ''}
    
    <!-- 🔥 NEW: Use Case Positioning -->
    ${summary.useCase ? card('🎯 Best Use Cases', `
      <div class="use-case-section">
        <div class="use-case-primary">
          <strong>Primary:</strong>
          <p>${summary.useCase.primary}</p>
        </div>
        <div class="use-case-recommended">
          <strong>Recommended For:</strong>
          <ul class="use-case-list">
            ${(summary.useCase.recommendedFor || []).map(uc => `<li>${uc}</li>`).join('')}
          </ul>
        </div>
      </div>
    `) : ''}
    
    <!-- Top Fixes (Priority Actions) -->
    ${fixRows ? card('🎯 Top Priority Fixes', fixRows) : ''}
    
    <!-- Risk Factors -->
    ${riskRows ? card('⚠️ Risk Factors', riskRows) : card('✅ No Major Risks', '<p>No significant risk factors detected.</p>')}
    
    <!-- Strengths -->
    ${strengthRows ? card('💪 Strengths', strengthRows) : ''}
    
    <!-- Detailed Metrics -->
    ${card('📊 Detailed Metrics', `
      <div class="metrics-grid">
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.prHealthScore >= 80 ? 'metric-good' : summary.metrics.prHealthScore >= 60 ? 'metric-warn' : 'metric-bad'}">
            ${summary.metrics.prHealthScore}
          </div>
          <div class="metric-label">PR Health Score</div>
        </div>
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.debtScore < 30 ? 'metric-good' : summary.metrics.debtScore < 60 ? 'metric-warn' : 'metric-bad'}">
            ${summary.metrics.debtScore}
          </div>
          <div class="metric-label">Technical Debt</div>
        </div>
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.criticalIssues === 0 ? 'metric-good' : 'metric-bad'}">
            ${summary.metrics.criticalIssues}
          </div>
          <div class="metric-label">Critical Issues</div>
        </div>
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.hasTests ? 'metric-good' : 'metric-bad'}">
            ${summary.metrics.hasTests ? '✓' : '✗'}
          </div>
          <div class="metric-label">Tests</div>
        </div>
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.hasCI ? 'metric-good' : 'metric-bad'}">
            ${summary.metrics.hasCI ? '✓' : '✗'}
          </div>
          <div class="metric-label">CI/CD</div>
        </div>
        <div class="metric-card">
          <div class="metric-value ${summary.metrics.hasDocs ? 'metric-good' : 'metric-warn'}">
            ${summary.metrics.hasDocs ? '✓' : '✗'}
          </div>
          <div class="metric-label">Documentation</div>
        </div>
      </div>
    `)}
    
    <!-- View Detailed Analysis -->
    <div class="detailed-analysis-hint">
      <p>💡 Use the module buttons above to view detailed analysis for each area</p>
    </div>
  `);
}

// ── 🔥 NEW: Render README ─────────────────────────────────────────────────────

function renderReadme(d) {
  showResults(`
    <div class="results-header">
      <h2>📄 Generated README</h2>
    </div>
    ${card('📝 README.md Content', `
      <div class="readme-preview">
        <pre class="readme-content">${escHtml(d.content)}</pre>
      </div>
      <div class="readme-actions">
        <button class="btn btn-primary" onclick="copyReadme()">📋 Copy to Clipboard</button>
        <p class="readme-info">Length: ${d.length} characters</p>
      </div>
    `)}
    <div class="readme-hint">
      <p>💡 Copy this content and save it as <code>README.md</code> in your repository root</p>
    </div>
  `);
  
  // Store for copy function
  window.currentReadme = d.content;
}

function copyReadme() {
  if (window.currentReadme) {
    navigator.clipboard.writeText(window.currentReadme).then(() => {
      alert('✅ README copied to clipboard!');
    }).catch(() => {
      alert('❌ Failed to copy. Please select and copy manually.');
    });
  }
}

// ── 🔥 NEW: Render Fixes ──────────────────────────────────────────────────────

function renderFixes(d) {
  const fixCards = (d.fixes || []).map((fix, i) => `
    <div class="fix-card fix-priority-${fix.priority}">
      <div class="fix-card-header">
        <span class="fix-card-number">${i + 1}</span>
        <h3 class="fix-card-title">${fix.title}</h3>
        <span class="badge badge-${fix.priority}">${fix.priority.toUpperCase()}</span>
      </div>
      
      <div class="fix-card-impact">
        <strong>💡 Impact:</strong>
        <p>${fix.impact}</p>
      </div>
      
      <div class="fix-card-steps">
        <strong>📋 Steps:</strong>
        <ol>
          ${fix.steps.map(step => `<li>${step}</li>`).join('')}
        </ol>
      </div>
      
      ${fix.code ? `
        <div class="fix-card-code">
          <strong>💻 Code/Configuration:</strong>
          <pre class="code-block">${escHtml(fix.code)}</pre>
        </div>
      ` : ''}
    </div>
  `).join('');

  showResults(`
    <div class="results-header">
      <h2>🛠 Fix My Repo</h2>
      <p class="results-subtitle">Actionable fixes to improve your repository</p>
    </div>
    ${card(`🎯 ${d.totalFixes} Fixes Generated`, fixCards)}
    <div class="fixes-hint">
      <p>💡 Apply these fixes in order of priority to improve your repository health</p>
    </div>
  `);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function escHtml(str) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
